### ISSUE TITLE
Show extension version

### ISSUE THREAD

**Issue by llaville** [underground-works/clockwork-app#30]
It could be interresting to show the current version of application. Useful when we provide screenshot to see what's wrong !
Actually we should open specific browser modules to see it !

**Comment by itsgoingd** [comment]
Hey, I was actually considering this. I'd also like to add some sort of "credits" listing all contributors & used third-party libraries.

Meanwhile you can find the installed version in the browser extensions/addons UI.

**Comment by llaville** [comment]
ping @itsgoingd ! Any news about this new feature ?

**Comment by itsgoingd** [comment]
yeah, worked on this a bit recently, i can't decide whether to go with the "credits" idea, since it is a bit more involved than i've expected. 

i'd need to fetch the data from github, packagist and npm, ideally store it outside the js bundle and load on demand when the credits screen is shown. seems like a lot of code for something pretty unnecessary, might just add the version number to settings ui and call it a day.
