### ISSUE TITLE
Showing only 30 lines of timeline

### ISSUE THREAD

**Issue by piranha** [underground-works/clockwork-app#36]
Is there a reason to limit to only 30 lines of timeline? On my bigger pages I have 70-80 lines of information and it's a pain to jump between them. :) Could this be made higher? Or maybe configurable?

**Comment by itsgoingd** [comment]
Hey, the pagination is there mainly as a performance optimisation, since Vue is pretty slow when rendering long lists esp. with sub-components.

The limit is pretty conservative, I think I'll increase it specifically for the timeline to 100 for now. That makes a lot of sense since Clockwork 4.1 shows a lot more data on the timeline.

Eventually I'd like to replace the pagination with some infinite-scroll type implementation.

**Comment by itsgoingd** [comment]
Included in Clockwork 4.1 release.
