### ISSUE TITLE
editor settings api

### ISSUE THREAD

**Issue by staabm** [underground-works/clockwork-app#37]
in our REDAXO CMS we integrated clockwork for a great debug experience.

the REDAXO CMS itself has a native editor integration similar to the one in clockwork.
for the best user experience we would want to sync our REDAXO CMS editor settings with the clockwork editor settigs, so the user does not need to configure the same thing in 2 different places:

![grafik](https://user-images.githubusercontent.com/120441/78991755-f743f600-7b39-11ea-9836-36d5117c7836.png)

is there some kind of api we could call to set the editor config and maybe even hide it from the settings panel?

**Comment by itsgoingd** [comment]
hey, cool to see clockwork used in another open-source project!

unfortunately there is no official api right now. there is a way to change the clockwork web app settings in javascript tho.

the settings are stored as a json object under `clockwork` key in local storage. you could easily overwrite them in any javascript running under the same domain, eg:

```js
let store

try {
    store = JSON.parse(localStorage.getItem('clockwork'))
} catch (e) {
    store = { settings: { global: {} } }
}

// overriding editor setting with a custom value
store.settings.global.editor = 'atom'

localStorage.setItem('clockwork', JSON.stringify(store))
```

this is not perfect, since the settings format is not part of the public api and can change, but it should work.

i might add some more explicit api to do this, but i would need to think about more use-cases.

let me know how the clockwork integration goes and if you have any other ideas or issues.
