### ISSUE TITLE
standalone: set remote url in localstorage

### ISSUE THREAD

**Issue by bloep** [underground-works/clockwork-app#38]
hey itsgoingd :wave: 

as discussed in discord it would be great if there is a way to configure the remote url via the config object in local storage.

https://github.com/underground-works/clockwork-app/blob/a371c5311a42f09e8f864d671b4521e71baab9a9/src/platform/standalone.js#L35-L37

**Comment by itsgoingd** [comment]
hey, i have an idea on how to go about generic vanilla web ui support.

wip implementation branch
https://github.com/itsgoingd/clockwork/tree/vanilla-web

usage example
https://gist.github.com/itsgoingd/767bbce0a2b7e4be5e0ddf9d75810ab2

the idea is to load the app inside an iframe.

first we copy the original web app into any public accessible path (`public/vendor/clockwork` in the example). then instead of letting user use it directly, we choose whatever url we actually want to use for the web ui (`public/clockwork-web.php` in the example) and return a minimal html page with a full-screen iframe pointing to the original web app.

this way we can use a custom url without worrying about the app assets (the relative paths are still valid inside the iframe document). we can also use this opportunity to send settings to the app.

in the wip implementation i'm loading the iframe app with a `?clockwork-path=` query string, which will be used as the api path if present (but we could also use postMessage, localStorage etc. to communicate with the iframe).

i feel like this approach might solve all your integration issues with the assets paths and the settings overrides.

(btw this solution is inspired by the original clockwork 1.x web ui implementation https://github.com/itsgoingd/clockwork-web :)

**Comment by staabm** [comment]
could `Clockwork::init` then also have parameters for the editor integratio, so we dont need to fiddle with the localstorage, like described in https://github.com/underground-works/clockwork-app/issues/37#issuecomment-612123597 ?

**Comment by itsgoingd** [comment]
i think it's better to implement on your side, the new api still simplifies your integration a lot, you can replace you custom build with something like:

```php
return str_replace('</body>', "{$injectedScripts}</body>", $clockwork->getWeb());
```

**Comment by bloep** [comment]
we created a fork (https://github.com/redaxo/clockwork-app) for our specific changes.
So there is no need anymore for this change.

Thank you :wink: .

**Comment by itsgoingd** [comment]
probably a good decision in the long run to enable better customization for your project 👍 

i'm always happy to look at whatever feature ideas you might have in the future to see if they would work upstream tho
